server:
  port: 10086

spring:
  application:
    name: wms-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 219.135.168.199:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:

        - id: route_user    #路由的id,没有规定规则但要求唯一,建议配合服务名
          uri: lb://wms-user     #匹配后提供服务的路由地址
          predicates:
            - Path=/user/** # 断言，路径相匹配的进行路由

        #openFeign配置
feign:
  httpclient:
    connection-timeout: 60000
    enabled: true
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: '*'