server:
  port: 2002

spring:
  application:
    name: ali-seata-storage
  cloud:
    alibaba:
      seata:
        #与seata配置一致
        #tx-service-group: ky_tx_group
        tx-service-group: wms_group
    nacos:
      discovery:
        #server-addr: cluster.local:80
        server-addr: 219.135.168.199:8848
    sentinel:
      transport:
        #配置sentinel的仪表盘地址
        dashboard: 219.135.168.199:9527
        port: 8719
      datasource:
        ds1:
          nacos:
            #server-addr: cluster.local:80
            server-addr: 219.135.168.199:8848
            dataId: ali-seata-storage
            data-type: json
            rule-type: flow
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    #    url: jdbc:mysql://kaiyu.work:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #    username: seata
    #    password: KY&seata56
    url: jdbc:mysql://kaiyu.work:3306/test_one_seatadb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: LYY&css1314

feign:
  sentinel:
    enabled: true
  hystrix:
    enabled: false
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    io:
      seata: info

management:
  endpoints:
    web:
      exposure:
        include: '*'


